name: Validate

on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          # cache: poetry
          python-version: 3.13

      - uses: snok/install-poetry@v1.4.1

      - run: poetry run ./scripts/lint.sh

  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          # cache: pipenv
          python-version: ${{ matrix.python-version }}

      - uses: snok/install-poetry@v1.4.1

      - run: pipenv run pytest
